In [23]:
import pandas as pd
pd.set_option('display.max_columns', 500)

url = 'https://github.com/DS3001/project_gss/raw/main/gss_chunk_1.parquet' # Create url to the chunk to be processed
df = pd.read_parquet(url) # Download chunk 1 of data
df.shape

(24130, 6694)

In [24]:
df.loc[:, ['year', 'id', 'age', 'sex', 'gunlaw', 'owngun', 'pistol', 'shotgun', 'rifle', 'rowngun', 'hunt']].head(40)

    year  id   age     sex  gunlaw owngun pistol shotgun rifle rowngun hunt
0   1972   1  23.0  female   favor    NaN    NaN     NaN   NaN     NaN  NaN
1   1972   2  70.0    male   favor    NaN    NaN     NaN   NaN     NaN  NaN
2   1972   3  48.0  female   favor    NaN    NaN     NaN   NaN     NaN  NaN
3   1972   4  27.0  female   favor    NaN    NaN     NaN   NaN     NaN  NaN
4   1972   5  61.0  female   favor    NaN    NaN     NaN   NaN     NaN  NaN
5   1972   6  26.0    male  oppose    NaN    NaN     NaN   NaN     NaN  NaN
6   1972   7  28.0    male   favor    NaN    NaN     NaN   NaN     NaN  NaN
7   1972   8  27.0    male   favor    NaN    NaN     NaN   NaN     NaN  NaN
8   1972   9  21.0  female   favor    NaN    NaN     NaN   NaN     NaN  NaN
9   1972  10  30.0  female   favor    NaN    NaN     NaN   NaN     NaN  NaN
10  1972  11  30.0  female   favor    NaN    NaN     NaN   NaN     NaN  NaN
11  1972  12  56.0    male   favor    NaN    NaN     NaN   NaN     NaN  NaN
12  1972  13  54.0    male   favor    NaN    NaN     NaN   NaN     NaN  NaN
13  1972  14  49.0  female   favor    NaN    NaN     NaN   NaN     NaN  NaN
14  1972  15  41.0    male  oppose    NaN    NaN     NaN   NaN     NaN  NaN
15  1972  16  54.0    male  oppose    NaN    NaN     NaN   NaN     NaN  NaN
16  1972  17  24.0    male  oppose    NaN    NaN     NaN   NaN     NaN  NaN
17  1972  18  62.0  female  oppose    NaN    NaN     NaN   NaN     NaN  NaN
18  1972  19  46.0  female  oppose    NaN    NaN     NaN   NaN     NaN  NaN
19  1972  20  21.0  female   favor    NaN    NaN     NaN   NaN     NaN  NaN
20  1972  21  57.0    male     NaN    NaN    NaN     NaN   NaN     NaN  NaN
21  1972  22  58.0    male  oppose    NaN    NaN     NaN   NaN     NaN  NaN
22  1972  23  21.0    male   favor    NaN    NaN     NaN   NaN     NaN  NaN
23  1972  24  26.0  female   favor    NaN    NaN     NaN   NaN     NaN  NaN
24  1972  25  71.0  female   favor    NaN    NaN     NaN   NaN     NaN  NaN
25  1972  26  53.0  female   favor    NaN    NaN     NaN   NaN     NaN  NaN
26  1972  27  42.0    male  oppose    NaN    NaN     NaN   NaN     NaN  NaN
27  1972  28  42.0  female  oppose    NaN    NaN     NaN   NaN     NaN  NaN
28  1972  29  20.0    male   favor    NaN    NaN     NaN   NaN     NaN  NaN
29  1972  30  23.0    male   favor    NaN    NaN     NaN   NaN     NaN  NaN
30  1972  31  26.0    male   favor    NaN    NaN     NaN   NaN     NaN  NaN
31  1972  32  25.0  female  oppose    NaN    NaN     NaN   NaN     NaN  NaN
32  1972  33  26.0    male   favor    NaN    NaN     NaN   NaN     NaN  NaN
33  1972  34  78.0  female   favor    NaN    NaN     NaN   NaN     NaN  NaN
34  1972  35  21.0    male   favor    NaN    NaN     NaN   NaN     NaN  NaN
35  1972  36  27.0    male   favor    NaN    NaN     NaN   NaN     NaN  NaN
36  1972  37  58.0  female  oppose    NaN    NaN     NaN   NaN     NaN  NaN
37  1972  38  35.0  female  oppose    NaN    NaN     NaN   NaN     NaN  NaN
38  1972  39  58.0    male  oppose    NaN    NaN     NaN   NaN     NaN  NaN
39  1972  40  51.0  female  oppose    NaN    NaN     NaN   NaN     NaN  NaN

In [25]:
df.loc[:, ['year', 'id', 'age', 'sex', 'gunlaw', 'owngun', 'pistol', 'shotgun', 'rifle', 'rowngun', 'hunt']].tail(40)

,year,id,age,sex,gunlaw,owngun,pistol,shotgun,rifle,rowngun,hunt
24090,1989,735,75.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24091,1989,736,78.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24092,1989,737,58.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24093,1989,738,33.0,female,oppose,yes,yes,yes,yes,yes,"yes, both do"
24094,1989,739,25.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24095,1989,740,65.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24096,1989,741,23.0,male,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24097,1989,742,23.0,male,oppose,yes,yes,no,no,yes,"no, neither r nor spouse hunts"
24098,1989,743,46.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24099,1989,744,80.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24100,1989,745,80.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24101,1989,746,77.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24102,1989,747,25.0,male,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24103,1989,748,32.0,male,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24104,1989,749,32.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24105,1989,750,36.0,male,favor,yes,yes,no,no,yes,"no, neither r nor spouse hunts"
24106,1989,751,70.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24107,1989,752,76.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24108,1989,753,76.0,female,favor,yes,no,no,no,yes,"no, neither r nor spouse hunts"
24109,1989,754,63.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24110,1989,755,76.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24111,1989,756,72.0,male,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24112,1989,757,63.0,female,favor,yes,yes,yes,yes,yes,"no, neither r nor spouse hunts"
24113,1989,758,44.0,female,favor,yes,yes,no,no,yes,"no, neither r nor spouse hunts"
24114,1989,759,41.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24115,1989,760,54.0,male,oppose,yes,yes,yes,no,yes,"no, neither r nor spouse hunts"
24116,1989,761,46.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24117,1989,762,34.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24118,1989,763,31.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24119,1989,764,20.0,male,favor,yes,yes,yes,yes,yes,"yes, respondent does"
24120,1989,765,34.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24121,1989,766,66.0,male,favor,yes,yes,no,no,yes,"no, neither r nor spouse hunts"
24122,1989,767,NaN,female,favor,yes,no,yes,no,no,"no, neither r nor spouse hunts"
24123,1989,768,19.0,female,oppose,yes,no,no,yes,no,"no, neither r nor spouse hunts"
24124,1989,769,34.0,male,oppose,yes,yes,yes,yes,yes,"yes, both do"
24125,1989,770,53.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24126,1989,771,35.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24127,1989,772,25.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24128,1989,773,74.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24129,1989,774,21.0,male,favor,yes,no,no,yes,yes,"yes, respondent does"

In [26]:
url = 'https://github.com/DS3001/project_gss/raw/main/gss_chunk_2.parquet' # Create url to the chunk to be processed
df = pd.read_parquet(url) # Download chunk 1 of data
df.shape

(24130, 6694)

In [27]:
df.loc[:, ['year', 'id', 'age', 'sex', 'gunlaw', 'owngun', 'pistol', 'shotgun', 'rifle', 'rowngun', 'hunt']].head(40)

,year,id,age,sex,gunlaw,owngun,pistol,shotgun,rifle,rowngun,hunt
0,1989,775,62.0,male,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
1,1989,776,32.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1989,777,80.0,female,favor,yes,yes,no,no,yes,"no, neither r nor spouse hunts"
3,1989,778,19.0,male,oppose,no,no,no,no,NaN,"no, neither r nor spouse hunts"
4,1989,779,67.0,female,oppose,no,no,no,no,NaN,"no, neither r nor spouse hunts"
5,1989,780,39.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
6,1989,781,25.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1989,782,71.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1989,783,59.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1989,784,82.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
10,1989,785,56.0,male,oppose,yes,yes,yes,yes,NaN,"no, neither r nor spouse hunts"
11,1989,786,48.0,female,oppose,yes,no,no,yes,yes,"no, neither r nor spouse hunts"
12,1989,787,34.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1989,788,60.0,male,favor,yes,no,no,yes,yes,"no, neither r nor spouse hunts"
14,1989,789,27.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1989,790,24.0,male,favor,yes,yes,yes,yes,yes,"no, neither r nor spouse hunts"
16,1989,791,65.0,male,favor,yes,yes,yes,yes,yes,"no, neither r nor spouse hunts"
17,1989,792,69.0,male,oppose,yes,yes,yes,yes,yes,"yes, respondent does"
18,1989,793,26.0,male,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
19,1989,794,57.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1989,795,62.0,male,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
21,1989,796,45.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
22,1989,797,64.0,male,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
23,1989,798,36.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1989,799,20.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1989,800,20.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1989,801,44.0,male,oppose,yes,no,yes,no,yes,"no, neither r nor spouse hunts"
27,1989,802,40.0,male,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
28,1989,803,47.0,male,oppose,yes,yes,no,no,yes,"no, neither r nor spouse hunts"
29,1989,804,49.0,female,oppose,yes,no,no,yes,yes,"no, neither r nor spouse hunts"
30,1989,805,42.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,1989,806,19.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
32,1989,807,80.0,female,NaN,no,no,no,no,NaN,"no, neither r nor spouse hunts"
33,1989,808,37.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,1989,809,61.0,female,oppose,yes,no,no,yes,no,"no, neither r nor spouse hunts"
35,1989,810,40.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,1989,811,30.0,female,favor,yes,no,no,yes,no,"yes, spouse does"
37,1989,812,83.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
38,1989,813,34.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,1989,814,60.0,female,favor,yes,yes,yes,no,no,"no, neither r nor spouse hunts"

In [28]:
df.loc[:, ['year', 'id', 'age', 'sex', 'gunlaw', 'owngun', 'pistol', 'shotgun', 'rifle', 'rowngun', 'hunt']].tail(40)

,year,id,age,sex,gunlaw,owngun,pistol,shotgun,rifle,rowngun,hunt
24090,2006,1711,60.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24091,2006,1712,58.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24092,2006,1713,41.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24093,2006,1714,29.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24094,2006,1715,53.0,female,oppose,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24095,2006,1716,35.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24096,2006,1717,66.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24097,2006,1718,59.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24098,2006,1719,46.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24099,2006,1720,30.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24100,2006,1721,48.0,male,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24101,2006,1722,65.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24102,2006,1723,24.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24103,2006,1724,37.0,female,NaN,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24104,2006,1725,35.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24105,2006,1726,33.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24106,2006,1727,52.0,male,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24107,2006,1728,31.0,female,NaN,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24108,2006,1729,45.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24109,2006,1730,44.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24110,2006,1731,88.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24111,2006,1732,35.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24112,2006,1733,48.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24113,2006,1734,88.0,male,NaN,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24114,2006,1735,58.0,female,NaN,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24115,2006,1736,60.0,male,oppose,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24116,2006,1737,36.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24117,2006,1738,58.0,male,favor,yes,yes,yes,yes,yes,"yes, respondent does"
24118,2006,1739,26.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24119,2006,1740,49.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24120,2006,1741,41.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24121,2006,1742,72.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24122,2006,1743,59.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24123,2006,1744,67.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24124,2006,1745,33.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24125,2006,1746,40.0,male,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24126,2006,1747,49.0,female,oppose,yes,no,yes,no,yes,"no, neither r nor spouse hunts"
24127,2006,1748,44.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24128,2006,1749,48.0,male,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24129,2006,1750,44.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
url = 'https://github.com/DS3001/project_gss/raw/main/gss_chunk_3.parquet' # Create url to the chunk to be processed
df = pd.read_parquet(url) # Download chunk 1 of data
df.shape

(24130, 6694)

In [30]:
df.loc[:, ['year', 'id', 'age', 'sex', 'gunlaw', 'owngun', 'pistol', 'shotgun', 'rifle', 'rowngun', 'hunt']].head(40)

,year,id,age,sex,gunlaw,owngun,pistol,shotgun,rifle,rowngun,hunt
0,2006,1751,48.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2006,1752,25.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2006,1753,42.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2006,1754,24.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2006,1755,24.0,female,favor,no,no,no,no,NaN,"yes, spouse does"
5,2006,1756,31.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2006,1757,46.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2006,1758,52.0,female,favor,yes,no,no,yes,no,"yes, spouse does"
8,2006,1759,42.0,male,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
9,2006,1760,50.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2006,1761,32.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2006,1762,48.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
12,2006,1763,57.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2006,1764,62.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2006,1765,66.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2006,1766,34.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2006,1767,30.0,male,oppose,no,no,no,no,NaN,"no, neither r nor spouse hunts"
17,2006,1768,27.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2006,1769,59.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2006,1770,19.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2006,1771,23.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
21,2006,1772,50.0,male,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
22,2006,1773,35.0,female,oppose,yes,no,yes,no,no,"no, neither r nor spouse hunts"
23,2006,1774,44.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2006,1775,78.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2006,1776,33.0,male,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
26,2006,1777,21.0,male,oppose,no,no,no,no,NaN,"no, neither r nor spouse hunts"
27,2006,1778,77.0,male,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
28,2006,1779,70.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
29,2006,1780,69.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,2006,1781,26.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
31,2006,1782,27.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,2006,1783,24.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
33,2006,1784,30.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
34,2006,1785,89.0,male,oppose,no,no,no,no,NaN,"no, neither r nor spouse hunts"
35,2006,1786,37.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,2006,1787,68.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,2006,1788,83.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,2006,1789,61.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,2006,1790,72.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"

In [31]:
df.loc[:, ['year', 'id', 'age', 'sex', 'gunlaw', 'owngun', 'pistol', 'shotgun', 'rifle', 'rowngun', 'hunt']].tail(40)

,year,id,age,sex,gunlaw,owngun,pistol,shotgun,rifle,rowngun,hunt
24090,2022,3506,54.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24091,2022,3507,53.0,male,favor,yes,yes,yes,yes,yes,"yes, respondent does"
24092,2022,3508,80.0,male,favor,no,no,no,no,NaN,"yes, respondent does"
24093,2022,3509,78.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24094,2022,3510,86.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24095,2022,3511,67.0,male,oppose,yes,yes,yes,yes,yes,"yes, respondent does"
24096,2022,3512,27.0,male,favor,no,no,no,no,NaN,"yes, respondent does"
24097,2022,3513,51.0,male,oppose,yes,yes,yes,yes,yes,"no, neither r nor spouse hunts"
24098,2022,3514,77.0,male,oppose,yes,no,yes,yes,yes,"no, neither r nor spouse hunts"
24099,2022,3515,67.0,female,oppose,yes,yes,yes,yes,yes,"yes, spouse does"
24100,2022,3516,38.0,female,favor,yes,yes,yes,yes,yes,"yes, spouse does"
24101,2022,3517,25.0,male,oppose,no,no,no,no,NaN,"yes, respondent does"
24102,2022,3518,NaN,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24103,2022,3519,74.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24104,2022,3520,85.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24105,2022,3521,58.0,male,favor,yes,no,yes,yes,yes,"yes, respondent does"
24106,2022,3522,30.0,male,oppose,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24107,2022,3523,74.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24108,2022,3524,29.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24109,2022,3525,29.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24110,2022,3526,78.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24111,2022,3527,63.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24112,2022,3528,71.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24113,2022,3529,72.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24114,2022,3530,60.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24115,2022,3531,64.0,female,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24116,2022,3532,61.0,male,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24117,2022,3533,66.0,female,favor,yes,yes,yes,yes,yes,"no, neither r nor spouse hunts"
24118,2022,3534,49.0,male,favor,yes,no,no,yes,yes,"no, neither r nor spouse hunts"
24119,2022,3535,50.0,male,favor,yes,no,no,yes,yes,"yes, both do"
24120,2022,3536,69.0,male,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24121,2022,3537,66.0,male,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24122,2022,3538,78.0,male,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24123,2022,3539,73.0,male,favor,no,no,no,no,NaN,"yes, respondent does"
24124,2022,3540,84.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24125,2022,3541,22.0,female,favor,yes,yes,yes,yes,no,"no, neither r nor spouse hunts"
24126,2022,3542,29.0,female,oppose,yes,yes,yes,yes,no,"no, neither r nor spouse hunts"
24127,2022,3543,32.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24128,2022,3544,49.0,female,favor,no,no,no,no,NaN,"no, neither r nor spouse hunts"
24129,2022,3545,50.0,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN